# Generated by Django 4.2.23 on 2025-09-14 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
