# Generated by Django 4.2.23 on 2025-10-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_borough'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borough',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
