# Generated by Django 4.2.23 on 2025-10-12 13:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_borough_latitude_borough_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='border',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
