# Generated by Django 4.2.23 on 2025-10-13 11:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_borough_border'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borough',
            name='border',
        ),
        migrations.CreateModel(
            name='BoroughBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('borough', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='border_data', to='listings.borough')),
            ],
        ),
    ]
